channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=24.3.1
- pip:
  - mlflow==2.14.0rc0
  - cloudpickle==3.1.0
  - numpy==1.26.4
  - packaging==24.2
  - pandas==2.2.2
  - pyyaml==5.4.1
  - scikit-learn==1.5.2
  - scipy==1.14.1
name: mlflow-env
